### ISSUE TITLE
Проблема с белым списком слов / Issue with word whitelist

### ISSUE THREAD

**Issue by Ghostlyr** [DenAbr/ChatGuard#1]
RU:
Обнаружил проблему с добавленными в "белый список" словами - плагин полностью исключает слово из проверок, даже если в него приписать другие запрещенные слова, которых нет в белом списке. Допустим, слово `[лl]([оo0]|[аa@])[хx]` занесено в swearwords, при обычном написании оно блокируется, так же запрещено и блокируется слово "жопа", однако, если взять какое-либо слово из белого списка, `пло(хо|хой|хое|ха|хая|хи|хие|хим|хого|хом|хому)`, например, и соединить его с любым из слов с этого черного списка, то плагин его пропускает - "плохаяжопа" попадает в чат.
Возможно, это мой косяк, мог что-то не так понять. Если так, извините за беспокойство.

EN:
I found a problem with words the added to the "whitelist" - plugin excludes a words from the checks, even if it attributed to other forbidden words that are not in the whitelist. For example, the word "shit" recorded in swearwords, in normal writing is blocked, as is prohibited and is blocked by the word "ass", but if you take any word from white list "shitship", for example, and connect it with any of the words with this black list, then plugin it passes - "shitshipass" enters the chat.
Perhaps it is my fault, maybe i'm something could not understand. If so, sorry to trouble you,

**Comment by DenAbr** [comment]
Проблема понятна, буду разбираться, когда освобожусь.

**Comment by DenAbr** [comment]
Поправил, проверяйте.

**Comment by Ghostlyr** [comment]
Да, теперь маты не проходят. Благодарю.

**Comment by Ghostlyr** [comment]
Все же обнаружился небольшой косяк. Проблема с проверкой регистра букв для слов из белого списка:

```
 [ChatGuard] [DEBUG 1] Player's CD 0
 [ChatGuard] [DEBUG 1] SwearFilter found: лох
 [ChatGuard] [DEBUG 2] SwearFilter: got whitelist pattern плохо for string пЛоХо
 [ChatGuard] [DEBUG 2] SwearFilter: пЛоХо without плохо - пЛоХо
 [ChatGuard] [DEBUG 2] SwearFilter: пЛоХо is not swearing. Skipping.
 Player: пЛоХо
 [ChatGuard] [DEBUG 1] Player's CD 0
 [ChatGuard] [DEBUG 1] SwearFilter found: лох
 [ChatGuard] [DEBUG 2] SwearFilter: got whitelist pattern плохо for string плохО
 [ChatGuard] [DEBUG 2] SwearFilter: плохО without плохо - плохО
 [ChatGuard] [DEBUG 2] SwearFilter: плохО is swearing. Do not whitelist.
 [WARN] Swear: Player: плохО
```

**Comment by DenAbr** [comment]
Добавил исправление
