### ISSUE TITLE
mute command isnt working from console in case of the reason has spaces

### ISSUE THREAD

**Issue by DmitryRendov** [DenAbr/ChatGuard#4]
failed:
`>cg mute newplayer 60  More adequate 123

[07:01:21 INFO]: /cg mute [Player] ([Time] (Reason)) - Mute player for some reason
`

success:
`>cg mute newplayer 60 More-adequate-123

[07:02:49 INFO]: Игрок замьючен за 1 мин.. Повод: More-adequate-123
`

**Comment by DenAbr** [comment]
Try [this](https://github.com/DenAbr/ChatGuard/blob/master/ChatGuard.jar?raw=true)

**Comment by DmitryRendov** [comment]
@DenAbr works fine now. Thank you for the prompt fix)
Can be closed.
