### ISSUE TITLE
Проблема с белым списком символов / Character whitelist issue

### ISSUE THREAD

**Issue by Ghostlyr** [DenAbr/ChatGuard#5]
При наличии сторонних символов в сообщении, плагин отфильтровывает его, однако не производит проверку по словарю.

Например:
При отправке сообщения `плохоеΉсловоизсловаря`, плагин возвращает его как `плохоесловоизсловаря`, соответственно, запрещенное слово проскакивает в чат в "чистом" виде.

If in the message presents characters, that is not listed in whitelist, plugin cuts off it, but does not check it by other filters.

For example:
When sending a message `badΉword` plugin returns it as a `badword` whereupon banned word skips the to chat in "pure" form.

**Comment by Leymooo** [comment]
Также последняя версия с гитхаба, почему то постоянно при чате или команде выводит в консоль "false"

**Comment by Dimatert9** [comment]
![image](https://cloud.githubusercontent.com/assets/8667294/21397093/193ea6e2-c7ab-11e6-84f6-2c2f8a294fb4.png)

**Comment by DenAbr** [comment]
Собрал без этого сообщения

**Comment by Leymooo** [comment]
спасибо

**Comment by Ghostlyr** [comment]
Увы, мою проблему исправление не решило.
Отмечу, что при включенном "Hard mode" сообщения фильтруются правильно. (и на ранних версиях тоже)

**Comment by DenAbr** [comment]
Не подтверждаю. 
В ранних и текущей версии всё работает корректно, при стандартной конфигурации
