### ISSUE TITLE
Disable caps-lock filter for signs / Отключить фильтр caps-lock для табличек

### ISSUE THREAD

**Issue by Ghostlyr** [DenAbr/ChatGuard#6]
`en`
I think is not necessary to filter CAPS mesages on the signs, it just creates discomfort to players.

`ru`
Мне кажется, никакой надобности в этом фильтре на табличках нет, только игрокам доставляет неудобств.

**Comment by DenAbr** [comment]
Сделал

**Comment by tvchd** [comment]
Неработает же
Все-равно блокирует капс
